"""Initial migration

Revision ID: 2c031bc8dbae
Revises: 
Create Date: 2023-04-09 21:06:19.094384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c031bc8dbae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Specialty', sa.String(length=100), nullable=False),
    sa.Column('About', sa.Text(), nullable=False),
    sa.Column('Hospital', sa.String(length=100), nullable=False),
    sa.Column('Location', sa.String(length=100), nullable=True),
    sa.Column('Special_Interests', sa.String(length=100), nullable=True),
    sa.Column('Treatments_Offered', sa.String(length=100), nullable=True),
    sa.Column('Work_Experience', sa.String(length=100), nullable=True),
    sa.Column('Image_Src', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('Users')
    op.drop_table('Doctors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doctors',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Specialty', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('About', mysql.TEXT(), nullable=True),
    sa.Column('Hospital', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Special_Interests', mysql.TEXT(), nullable=True),
    sa.Column('Treatments_Offered', mysql.TEXT(), nullable=True),
    sa.Column('Work_Experience', mysql.TEXT(), nullable=True),
    sa.Column('Image_Src', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.TEXT(), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('doctor')
    # ### end Alembic commands ###
